name: Build and deploy to GitHub Pages with Jekyll

on:
  push:
    branches:
      - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  changes:
     runs-on: ubuntu-latest
     outputs:
       markdown: ${{ steps.check.outputs.markdown }}
       files: ${{ steps.check.outputs.files }}
     steps:
       - uses: actions/checkout@v6
         with:
           fetch-depth: 0

       - id: check
         run: |
           files="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.md$' || true)"

           {
             echo "files<<EOF"
             echo "$files"
             echo "EOF"
           } >> "$GITHUB_OUTPUT"
           
           if [[ -n "$files" ]]; then
             echo "markdown=true" >> "$GITHUB_OUTPUT"
           else
             echo "markdown=false" >> "$GITHUB_OUTPUT"
           fi

  # Scrape job
  scrape:
    needs: changes
    if: needs.changes.outputs.markdown == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install recipe-scrapers

      - name: Identify valid recipe files
        env:
          CHANGED_FILES: ${{ needs.changes.outputs.files }}
        run: |
          echo "LINKS_BY_FILE = {" > ./.github/filtered_links.py
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            # Extract non-YAML body (everything after second --- except empty lines)
            body=$(awk 'f{print} /^---/{c++} c==2{f=1}' "$file" | sed '/^$/d')

            # make sure there nothing besides the link
            if [[ -n "${body//\<*\>/}" ]]; then
              continue
            fi

            link=$(echo "$body" | sed 's/[<>]//g')
            
            # validate link (excluding YouTube/Instagram) and write to file
            if [[ "$link" =~ ^https?:// ]]; then
                echo "    \"$file\": \"$link\"," >> ./.github/filtered_links.py
            fi
          done <<< "$CHANGED_FILES"
          echo "}" >> ./.github/filtered_links.py

      - name: Scrape and update files
        run: |
          python ./.github/scrape_and_update.py

      - name: Commit to review branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B scraped-recipes
          git add **/*.md
          # Only commit and push if there are staged changes. 
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Scraped recipe data and updated files"
            git push origin scraped-recipes --force
          fi
  
  # Update the index and service worker
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Generate index.html
        run: bash ./.github/generate_index.sh

      - name: Update sw.js
        run: bash ./.github/update-sw.sh

      - name: Commit and push changes
        run: |
          VERSION=$(grep "var VERSION" sw.js | sed -E "s/.*'version_([0-9]+)'.*/\1/")
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html sw.js
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update index and sw.js to ${VERSION}"
            git push
          fi

  # Build job
  build:
    needs: [scrape, update]
    if: always()
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main
      - name: Download minima theme
        run: |
          wget -O _sass/minima_solarized.scss https://raw.githubusercontent.com/jekyll/minima/refs/heads/master/_sass/minima/skins/solarized.scss
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: always()
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
